### ISSUE TITLE
Uncaught TypeError when creating a conversation

### ISSUE THREAD

**Issue by scr4bble** [helpscout/helpscout-api-php#119]
Exception occurs when I try to create a conversation.
The code works fine on Fedora (PHP 7.2.15) but failing on Centos (PHP 7.1.26)
Dependencies installed by composer in both cases (I can provide also the composer.lock file if needed).

```
$ cat composer.json 
{
    "require": {
        "helpscout/api": "^2.0",
        "php-http/guzzle6-adapter": "^2.0"
    }
}
```

`$conv_id = $client->conversations()->create($conversation);`

```
E_ERROR: Uncaught TypeError: Return value of HelpScout\Api\Http\Hal\HalDocument::getEmbedded() must be of the type array, object returned in mail-integration/vendor/helpscout/api/src/Http/Hal/HalDocument.php:49
Stack trace:
#0 mail-integration/vendor/helpscout/api/src/Http/Hal/HalDeserializer.php(93): HelpScout\Api\Http\Hal\HalDocument->getEmbedded('errors')
#1 mail-integration/vendor/helpscout/api/src/Http/Handlers/ValidationHandler.php(21): HelpScout\Api\Http\Hal\HalDeserializer::deserializeError(Object(HelpScout\Api\Http\Hal\HalDocument))
#2 mail-integration/vendor/guzzlehttp/promises/src/Promise.php(203): HelpScout\Api\Http\Handlers\ValidationHandler->HelpScout\Api\Http\Handlers\{closure}(Object(GuzzleHttp\Psr7\Response))
#3 /srv/w in mail-integration/vendor/helpscout/api/src/Http/Hal/HalDocument.php on line 49
```

Please take a look as soon as possible. It is quite a blocking issue.

**Comment by scr4bble** [comment]
So, it looks like the problem occurs, when Tag with empty string in **name** argument happens to get into the tags collection.

Maybe something for validation..

```
object(HelpScout\Api\Conversations\Conversation)[238]
  private 'id' => null
  private 'threadCount' => null
  private 'autoReplyEnabled' => boolean false
  private 'number' => null
  private 'type' => string 'email' (length=5)
  private 'imported' => boolean false
  private 'assignTo' => null
  private 'folderId' => null
  private 'status' => string 'closed' (length=6)
  private 'state' => null
  private 'subject' => string 'STOP!' (length=5)
  private 'preview' => null
  private 'mailboxId' => int 42
  private 'assignee' => null
  private 'closedAt' => null
  private 'closedBy' => null
  private 'userUpdatedAt' => null
  private 'waitingSince' => null
  private 'tags' => 
    object(HelpScout\Api\Entity\Collection)[245]
      private 'storage' (ArrayObject) => 
        array (size=2)
          0 => 
            object(HelpScout\Api\Tags\Tag)[247]
              private 'id' => null
              private 'color' => null
              private 'name' => string '' (length=0)
              private 'slug' => null
              private 'createdAt' => null
              private 'updatedAt' => null
              private 'ticketCount' => null
          1 => 
            object(HelpScout\Api\Tags\Tag)[248]
              private 'id' => null
              private 'color' => null
              private 'name' => string 'sent-via-api' (length=12)
              private 'slug' => null
              private 'createdAt' => null
              private 'updatedAt' => null
              private 'ticketCount' => null

```

**Comment by bkuhl** [comment]
What version of the SDK are you using?  I'm wondering if https://github.com/helpscout/helpscout-api-php/releases/tag/2.0.4 resolved this...

**Comment by scr4bble** [comment]
From composer.lock it looks like it is version 2.1.0

```
{
            "name": "helpscout/api",
            "version": "2.1.0",
            "source": {
                "type": "git",
                "url": "https://github.com/helpscout/helpscout-api-php.git",
                "reference": "e3611daebcc6a63b5a8b118b20c649ddfabde988"
            },
```

**Comment by bkuhl** [comment]
I was able to reproduce this by omitting the tag name as well.  The SDK is expecting to have an Error but in this case there isn't one provided by the API.  I'm going to follow up on this internally before considering any bug fixes on the SDK side because I'd expect to see an error message in the json response.

**Comment by bkuhl** [comment]
We've confirmed this is actually caused by a bug on our end where the error message was not correctly translated from one of our internal services to our public API.  We've put it in our backlog to address, but won't be making changes to the SDK to handle this scenario since we should always expect an error message back.
