### ISSUE TITLE
Can't update customers who have an address

### ISSUE THREAD

**Issue by Sleavely** [helpscout/helpscout-api-php#12]
I could update this customer's name a few minutes ago, but when I added address and a second email adress through the "Edit customer profile" page I started getting HTTP 400.

Below is the customer object as printed by `$customer->toJSON();` just before I call the API, along with my code and the exception. Am I doing something horribly wrong?

```json
{
  "id": 12138552,
  "firstName": "Tester",
  "lastName": "Sleavely",
  "photoUrl": "http:\/\/0.gravatar.com\/avatar\/8c88d8cf7e0b9ac9d5bfe6b900028673",
  "photoType": "gravatar",
  "gender": "unknown",
  "age": null,
  "organization": null,
  "jobTitle": null,
  "location": "\u00c4lta, SE",
  "createdAt": "2014-07-08T13:50:13Z",
  "modifiedAt": "2014-08-11T20:08:18Z",
  "background": null,
  "address": {
    "id": 165868,
    "lines": [
        "Env\u00e4gen 123"
    ],
    "city": "\u00c4lta",
    "state": null,
    "postalCode": "13831",
    "country": "SE",
    "createdAt": "2014-08-11T20:08:18Z",
    "modifiedAt": null
  },
  "socialProfiles": [],
  "emails": [{
      "id": 16975270,
      "value": "redacted@redacted.com",
      "type": null,
      "location": "work"
    }, {
      "id": 18890466,
      "value": "redacted.redacted@redacted.nu",
      "type": null,
      "location": "work"
    }
  ],
  "phones": [{
      "id": 16975271,
      "value": "+46001112233",
      "type": null,
      "location": "work"
    }
  ],
  "chats": [],
  "websites": []
}
```

```php
<?php
	$client = ApiClient::getInstance();
	$client->setKey('Redacted as hell! :)');

	$emailAddress = 'redacted@redacted.com';
	$customerCollection = $client->searchCustomersByEmail($emailAddress);
	$exists = $customerCollection && !empty($customerCollection->getItems());
	if($exists)
	{
		$customer = $customerCollection->getItems()[0]; // First one must be right. Right?!
		$customer = $client->getCustomer( $customer->getId() );
	}
	else
	{
		$customer = new \HelpScout\model\Customer();
	}

	// Set a new name for fun and glory
	$customer->setFirstName("Tester");
	$customer->setLastName("Sleavely");

	// The JSON sample comes from over here.
	// dd($customer->toJSON());

	if($exists)
	{
		$result = $client->updateCustomer($customer);
		// Now I have an exception on my hands. Not fun at all :(
	}
	else
	{
		$emailHome = new \HelpScout\model\customer\EmailEntry();
		$emailHome->setValue($emailAddress);
		$emailHome->setLocation('home');
		$customer->addEmail($emailHome);

		$result = $client->createCustomer($customer);
	}
```

```
[2014-08-11 23:40:57] production.ERROR: exception 'HelpScout\ApiException' with message 'The request was not formatted correctly' in C:\Git\helpscout-api-test\vendor\helpscout\api\src\HelpScout\ApiClient.php:654
Stack trace:
#0 C:\Git\helpscout-api-test\vendor\helpscout\api\src\HelpScout\ApiClient.php(892): HelpScout\ApiClient->checkStatus(400, 'PUT', 200)
#1 C:\Git\helpscout-api-test\vendor\helpscout\api\src\HelpScout\ApiClient.php(477): HelpScout\ApiClient->doPut('customers/12138...', '{"id":12138552,...', 200)
#2 C:\Git\helpscout-api-test\app\routes.php(53): HelpScout\ApiClient->updateCustomer(Object(HelpScout\model\Customer))
#3 [internal function]: {closure}()
#4 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#5 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#6 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Routing\Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#7 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#8 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#9 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#10 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#11 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#12 C:\Git\helpscout-api-test\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#13 C:\Git\helpscout-api-test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#14 C:\Git\helpscout-api-test\public\index.php(49): Illuminate\Foundation\Application->run()
#15 {main} [] []
```

**Comment by stevenwadejr** [comment]
Hey @Sleavely,

This is a 2 parter. There should be a fix being pushed soon to the public API that will solve this issue. In the meantime, release [1.4.0](https://github.com/helpscout/helpscout-api-php/tree/1.4.0) has updated error reporting and debugging support to be more verbose. That should help you debug this or other errors in the future.

We'll notify you and close this ticket when the API fix has been pushed.
