### ISSUE TITLE
Gets uncaught TypeError when no folder in the mailbox

### ISSUE THREAD

**Issue by wrmond** [helpscout/helpscout-api-php#186]
Will get uncaught TypeError when no folder in the mailbox

$mailbox_id = 'xxxx';
$mailboxRequest = (new MailboxRequest())->withFolders()->withFields();
$mailbox = $client->mailboxes()->get($mailbox_id, $mailboxRequest);

//===========

PHP Warning:  array_map(): Argument #2 should be an array in \vendor\helpscout\api\src\Http\Hal\HalDeserializer.php on line 62
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to HelpScout\Api\Http\Hal\HalPagedResources::__construct() must be of the type array, null given, called in \vendor\helpscout\api\src\Http\Hal\HalDeserializer.php on line 73 and defined in \vendor\helpscout\api\src\Http\Hal\HalPagedResources.php:19
Stack trace:
#0 \vendor\helpscout\api\src\Http\Hal\HalDeserializer.php(73): HelpScout\Api\Http\Hal\HalPagedResources->__construct(NULL, Object(HelpScout\Api\Http\Hal\HalLinks), Object(HelpScout\Api\Http\Hal\HalPageMetadata))
#1 \vendor\helpscout\api\src\Http\RestClient.php(159): HelpScout\Api\Http\Hal\HalDeserializer::deserializeResources('HelpScout\\Api\\M...', 'fields', Object(HelpScout\Api\Http\Hal\HalDocument))
#2 \vendor\helpscout\api\src\Entity\LinkedEntityLoader.php(69): Help in \vendor\helpscout\api\src\Http\Hal\HalPagedResources.php on line 19

**Comment by bkuhl** [comment]
Hey!  What version of the SDK are you using?  In [v2.3.8](https://github.com/helpscout/helpscout-api-php/releases/tag/2.3.8) we addressed some issues that are pretty similar to this one, I'm wondering if you're using an older version if updating would resolve the issue.

**Comment by wrmond** [comment]
Yes. It is version 2.3.8.

The problem is:
the json when 'fields' is empty
```
{
....
	"_embedded": {
		"fields": []
	},
.....
}
```

"fields": [] with be converted to a HalDocument but with empty data/links/embedded like this, in \HelpScout\Api\Http\Hal\HalDeserializer::deserializeResources() :

```
object(HelpScout\Api\Http\Hal\HalDocument)#82 (3) {
  ["data":"HelpScout\Api\Http\Hal\HalDocument":private]=>
  array(0) {
  }
  ["links":"HelpScout\Api\Http\Hal\HalDocument":private]=>
  object(HelpScout\Api\Http\Hal\HalLinks)#77 (1) {
    ["links":"HelpScout\Api\Http\Hal\HalLinks":private]=>
    array(0) {
    }
  }
  ["embedded":"HelpScout\Api\Http\Hal\HalDocument":private]=>
  array(0) {
  }
}
```

So for a mailbox without folders, the mailbox(HalDocument) has an embedded 'fields'(HalDocument but with empty data/links/embedded) .
mailbox(HalDocument) will return true for hasEmbedded('fields') even 'fields' is empty



Therefore, here is what i propose to change in \HelpScout\Api\Http\Hal\HalDeserializer::deserializeResources():

```
public static function deserializeResources($entityClass, string $rel, HalDocument $halDocument): HalResources
    {
	$resources = [];
        if ($halDocument->hasEmbedded($rel)) {
			$docEmbedded = $halDocument->getEmbedded($rel);
			if (is_array($docEmbedded)){
				$resources = array_map(function (HalDocument $embeddedDocument) use ($entityClass) {
					return self::deserializeResource($entityClass, $embeddedDocument);
				}, $docEmbedded);
			}
        } else {
            $resources = [];
        }
...
```
`array_map()` 2nd argument must be array type.
The above code will ensure `$resources` an array for `return new HalPagedResources($resources, ...`

**Comment by bkuhl** [comment]
An issue with the change your suggesting is embedded entities could be a single entity, so doing nothing if it's not an array doesn't solve that particular issue.

Can you supply me the mailboxId you're working with to produce this error?

**Comment by wrmond** [comment]
i guess it is nothing do with my working mailbox.

As you said 'embedded entities could be a single entity' , though in this case it is a HalDocument with empty data/links/embedded, 
this empty HalDocument  retrived from `$halDocument->getEmbedded($rel)` inside `HalDeserializer::deserializeResources()` is supplied to `array_map()`.
The empty HalDocument is not an array. But `array_map()` need an array in 2nd parameter.

`$halDocument->getEmbedded($rel)` normally this will return an array of HalDocument. But in this case it returns a HalDocument, not an array of HalDocument in which `array_map()` expected.
Then the whole `$resources = array_map(...., $halDocument->getEmbedded($rel));` returns `null` value to `$resources`.

Then follow the rest of the funciton,
 `$resources` gives to `new HalPagedResources($resources, ...)` , since $resource is `null` but constructor of HalPagedResources expects an `array` as first parameter, it will trigger a `TypeError` which make the whole endpoint api function php Fatal Error.

**Comment by bkuhl** [comment]
I understand it's empty in this scenario.  I could use the Mailbox ID though to help me recreate the problem because I added a test case with an empty embedded entity and it's not causing any issues, so I must be doing something different than what's actually happening.

**Comment by wrmond** [comment]
Understand. Then i guess it must be server / php env problem....

**Comment by bkuhl** [comment]
It's probably not, but I need the ID of the Mailbox you're working with so I can recreate the problem.  Please provide me that ID so I can look into this further.
