### ISSUE TITLE
hydration of attachment fails, if its not an image

### ISSUE THREAD

**Issue by michael-wolfram-tgh** [helpscout/helpscout-api-php#86]
Width and height of non image attachments equals 0 (tested with PDF- and DOCX- files). So the Assert::greaterThan test fails in setters of width and height:

https://github.com/helpscout/helpscout-api-php/blob/7a484b0f33e4a2eb48db4d47df8506f4715c4233/src/Conversations/Threads/Attachments/Attachment.php#L171

https://github.com/helpscout/helpscout-api-php/blob/7a484b0f33e4a2eb48db4d47df8506f4715c4233/src/Conversations/Threads/Attachments/Attachment.php#L185

Tested version: 2.0.1
Stacktrace:

```
#0 /vendor/webmozart/assert/src/Assert.php(545): HelpScout\Api\Assert\Assert::reportInvalidArgument('Expected a valu...')
#1 /vendor/helpscout/api/src/Conversations/Threads/Attachments/Attachment.php(170): Webmozart\Assert\Assert::greaterThan(0, 0)
#2 /vendor/helpscout/api/src/Conversations/Threads/Attachments/Attachment.php(86): HelpScout\Api\Conversations\Threads\Attachments\Attachment->setWidth(0)
#3 /vendor/helpscout/api/src/Conversations/Threads/Thread.php(148): HelpScout\Api\Conversations\Threads\Attachments\Attachment->hydrate(Array)
#4 /vendor/helpscout/api/src/Http/Hal/HalDeserializer.php(45): HelpScout\Api\Conversations\Threads\Thread->hydrate(Array, Array)
#5 /vendor/helpscout/api/src/Http/Hal/HalDeserializer.php(61): HelpScout\Api\Http\Hal\HalDeserializer::deserializeResource(Object(Closure), Object(HelpScout\Api\Http\Hal\HalDocument))
#6 [internal function]: HelpScout\Api\Http\Hal\HalDeserializer::HelpScout\Api\Http\Hal\{closure}(Object(HelpScout\Api\Http\Hal\HalDocument))
#7 /vendor/helpscout/api/src/Http/Hal/HalDeserializer.php(62): array_map(Object(Closure), Array)
#8 /vendor/helpscout/api/src/Http/RestClient.php(189): HelpScout\Api\Http\Hal\HalDeserializer::deserializeResources(Object(Closure), 'threads', Object(HelpScout\Api\Http\Hal\HalDocument))
#9 /vendor/helpscout/api/src/Conversations/Threads/ThreadsEndpoint.php(60): HelpScout\Api\Http\RestClient->getResources(Object(Closure), 'threads', '/v2/conversatio...')
#10 /vendor/helpscout/api/src/Conversations/Threads/ThreadsEndpoint.php(22): HelpScout\Api\Conversations\Threads\ThreadsEndpoint->loadThreads('/v2/conversatio...')
#11 /module/Accounting/src/Accounting/Model/HelpscoutDocumentModel.php(40): HelpScout\Api\Conversations\Threads\ThreadsEndpoint->list(xxx)

Fatal error:  Expected a value greater than 0. Got: 0 in /module/Accounting/src/Accounting/Model/HelpscoutDocumentModel.php on line 48
```

**Comment by bkuhl** [comment]
At the time when that validation was added it was from the context of creating attachments and fetching attachments such as in this case wasn't considered.  I've opened a PR to remove this validation.  Thanks for reporting this!

**Comment by kriskbx** [comment]
+1

**Comment by bkuhl** [comment]
Fixed in https://github.com/helpscout/helpscout-api-php/releases/tag/2.0.2
